### ISSUE TITLE
Lock icon confused state

### ISSUE THREAD

**Issue by licaon-kter** [tigase/beagle-im#86] opened 2021-07-12 14:33 UTC
macOS Catalina, beagle-beta, homebrew, 5.0 (128)

Settings, Encryption default: OMEMO

Open 1:1 chat, set lock to Unencrypted, lock icon is still closed(??), message is unencrypted
Set lock to Default _(should be OMEMO as setup in Setttings)_, lock icon is open(??), message is **unencrypted**
Set lock to OMEMO, lock icon is closed, message is encrypted

**Comment by hantu85** [comment] 2021-07-19 08:36
I've found the cause of this issue and it should be fixed in the next build.

**Comment by licaon-kter** [comment] 2021-07-19 09:09
Will this be pushed to `master` or `meet` will be merged and then?

**Comment by hantu85** [comment] 2021-07-19 09:12
`meet` will be merged but before this will be done, SiskinIM needs to be rebased on `meet` branch of `TigaseSwift` so we could then merge `meet` branch of TigaseSwift `master`

**Comment by hantu85** [comment] 2021-09-16 17:53
This issue is now fixed.

**Closed by hantu85** 2021-09-16 17:53 UTC
