### ISSUE TITLE
messages cut-off on right side

### ISSUE THREAD

**Issue by foss-** [tigase/beagle-im#80] opened 2021-03-27 09:45 UTC
Messages cut-off on the right-side. This is independent of window width and can be seen even when putting Beagle on full 15" laptop screen, as long as the message is longer than a single line.
<img width="97" alt="cut-off" src="https://user-images.githubusercontent.com/5708172/112716779-c0045b80-8ee8-11eb-85c4-968dfc288028.png">

**To Reproduce**

1. write or recieve some long messages (filling more than single line in window width)
2. look at right side of messages

This is easier to reproduce with a narrow window as more messagse will be more than one line and expose the problem.

**Expected behavior**

Messages should not be cut-off. 

 - macOS 11.2.3
 - Beagle 5.0 (117)

**Comment by hantu85** [comment] 2021-03-27 09:49
The issue was caused by changes in macOS 11.

Already solved in 2de00697d473d964c62819491e153eed6293cb09 and will be part of the next build.

**Closed by hantu85** 2021-03-27 09:49 UTC
