### ISSUE TITLE
CMD-Backspace should delete line, not close chat.

### ISSUE THREAD

**Issue by ls42** [tigase/beagle-im#16] opened 2020-02-28 07:37 UTC
**Describe the bug**
CMD-Backspace should delete line, not close chat. It is a common idiom on macOS to delete the current line of text. BeagleIM should use CMD-w to close the current chat, not CMD-Backspace.

**To Reproduce**
1. Enter a few words in a chat window
2. press aforementioned key combination.

**Expected behavior**
I expected that the text in entered disappeared.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: maOS 10.15.3
 - Version 3.6 [77]

**Comment by hantu85** [comment] 2020-04-15 14:55
I've just reviewed the behavior of apps on macOS (like Messages, Bear, Notes, Reminders, Mail) and each app has different behavior for CMD-Backspace, ie.:
* Messages: delete chat (same as BeagleIM)
* Bear: delete note
* Notes: delete line
* Reminder: delete line
* Mail: delete a message in the list view and delete a line in the message entering window

As you can see, CMD-Backspace means delete line or item (ie. note, chat), so usage of CMD-Backspace is correct in this case.

On the suggestion of usage CMD-W to close the chat - it is not how applications behave on macOS. CMD-W means "close the window" not close the chat!

I'm open on other alternatives for a shortcut to close a chat, but for now, closing on CMD-Backspace when the input field is empty looks like a most viable solution.

**Comment by ls42** [comment] 2020-04-15 15:09
CMD-W is widely used to close tabs, see any browser (safari, chrome, brave), or terminal emulators (iterm2 and terminal.app both). Text editors also do behave like this. VSCode to name one.

CMD-Backspace in **Apple Messages** behaves exactly as I described it: When a text-entry field is focused, CMD-Backspace deletes the whole lin. It does not close the current chat. Also you've mentioned a few apps that behave like this, i.e. when inside a text entry widget, CMD-Backspace removes a line. IMO that underlines that beagle-im should also remove a line, instead of closing the chat. 

More examples are Telegram and WhatsApp.

**Comment by hantu85** [comment] 2020-04-15 15:16
I've double-checked and **Apple Messages** closes chat (and even deletes the content of the chat) when text field has focus but it is empty and you pressed CMD-Backspace.

Due to that, I'm going to follow what Apple Messages does: if there is a line - remove it, if text filed is empty - close chat.

**Comment by ls42** [comment] 2020-04-15 15:19
> I'm going to follow what Apple Messages does: if there is a line - remove it, if text filed is empty - close chat.

Nice, thank you!

**Comment by jnaeff** [comment] 2020-04-19 17:47
It works great thanks for solving this!

**Closed** 2020-08-17 15:11 UTC

**Comment by neptuwunium** [comment] 2025-10-27 06:38
This seems to not work as intended/regressed, at least in 5.3.5 which is released 3 years after this fix.

Cmd + Backspace closes the chat regardless if the text input is focused, has content, has no content, has multiple lines of content.
